# Generated by Django 2.1.7 on 2019-07-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50, verbose_name='公司')),
                ('department', models.CharField(max_length=20, verbose_name='部门')),
                ('team', models.CharField(max_length=30, null=True, verbose_name='处室')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('duty', models.CharField(max_length=10, verbose_name='职务')),
            ],
            options={
                'verbose_name': '通讯录',
                'verbose_name_plural': '通讯录',
                'ordering': ('-organization',),
            },
        ),
    ]
