# Generated by Django 2.1.7 on 2019-07-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
