# Generated by Django 2.1.7 on 2019-07-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0002_contact_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='team',
        ),
    ]
