# Generated by Django 2.1.7 on 2019-07-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0003_remove_contact_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-organization', '-department', 'name'), 'verbose_name': '通讯录', 'verbose_name_plural': '通讯录'},
        ),
    ]
