# Generated by Django 2.1.7 on 2019-07-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0005_auto_20190730_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-organization', '-department', 'duty', 'phone'), 'verbose_name': '通讯录', 'verbose_name_plural': '通讯录'},
        ),
    ]
