# Generated by Django 2.1.7 on 2019-06-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baozhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=250, verbose_name='告警内容')),
                ('ip_source', models.TextField(verbose_name='源IP')),
                ('ip_dest', models.TextField(verbose_name='目的IP')),
                ('income_time', models.CharField(max_length=100, verbose_name='告警时间')),
                ('resource', models.CharField(max_length=100, verbose_name='告警来源')),
                ('level', models.CharField(max_length=100, verbose_name='告警级别')),
            ],
            options={
                'verbose_name': '深圳告警',
                'verbose_name_plural': '深圳告警数据表',
                'ordering': ('-income_time',),
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(verbose_name='IP地址')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('note', models.CharField(max_length=250, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'IP黑名单',
                'verbose_name_plural': 'IP黑名单',
                'ordering': ('ip',),
            },
        ),
        migrations.CreateModel(
            name='Fengdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=12, verbose_name='编号')),
                ('income_time', models.CharField(max_length=100, verbose_name='需求时间')),
                ('number_time', models.CharField(max_length=100, verbose_name='编号时间')),
                ('resource', models.CharField(max_length=100, verbose_name='需求来源')),
                ('ip_list', models.TextField(verbose_name='处置IP地址')),
                ('reason', models.CharField(max_length=250, verbose_name='处置原因')),
                ('excutor', models.CharField(max_length=50, verbose_name='处置者')),
                ('outcome', models.CharField(max_length=10, verbose_name='处置结果')),
                ('outcome_time', models.CharField(max_length=100, verbose_name='处理时间')),
                ('note', models.CharField(max_length=255, verbose_name='备注')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'HW封堵',
                'verbose_name_plural': 'HW封堵数据表',
                'ordering': ('-serial_number',),
            },
        ),
        migrations.CreateModel(
            name='Jichufd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=12, verbose_name='编号')),
                ('income_time', models.CharField(max_length=100, verbose_name='封堵时间')),
                ('resource', models.CharField(max_length=100, verbose_name='封堵者')),
                ('outcome', models.CharField(max_length=10, verbose_name='封堵结果')),
            ],
            options={
                'verbose_name': '深圳封堵',
                'verbose_name_plural': '深圳封堵数据表',
                'ordering': ('-serial_number',),
            },
        ),
        migrations.CreateModel(
            name='Jichujf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=12, verbose_name='编号')),
                ('income_time', models.CharField(max_length=100, verbose_name='解封时间')),
                ('resource', models.CharField(max_length=100, verbose_name='解封者')),
                ('outcome', models.CharField(max_length=10, verbose_name='解封结果')),
            ],
            options={
                'verbose_name': '深圳解封',
                'verbose_name_plural': '深圳解封数据表',
                'ordering': ('-serial_number',),
            },
        ),
        migrations.CreateModel(
            name='Jiefeng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=12, verbose_name='编号')),
                ('income_time', models.DateTimeField(verbose_name='需求时间')),
                ('resource', models.CharField(max_length=100, verbose_name='需求来源')),
                ('ip_list', models.TextField(verbose_name='解封IP地址')),
                ('excutor', models.CharField(max_length=50, verbose_name='解封者')),
                ('outcome', models.CharField(max_length=10, verbose_name='解封结果')),
                ('outcome_time', models.CharField(max_length=100, verbose_name='解封时间')),
                ('note', models.CharField(max_length=255, verbose_name='备注')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '解封',
                'verbose_name_plural': 'HW解封数据表',
                'ordering': ('-serial_number',),
            },
        ),
        migrations.CreateModel(
            name='PaiCha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=12, verbose_name='编号')),
                ('reason', models.CharField(max_length=250, verbose_name='原因')),
                ('ip_attack', models.TextField(verbose_name='攻击IP')),
                ('ip_attacked', models.TextField(verbose_name='被攻击IP')),
                ('location', models.CharField(max_length=250, verbose_name='物理位')),
                ('means', models.CharField(max_length=250, verbose_name='攻击手段')),
                ('guard', models.CharField(max_length=250, verbose_name='防护措施')),
                ('result', models.CharField(max_length=250, verbose_name='排查结果')),
                ('income_time', models.CharField(max_length=100, verbose_name='需求时间')),
                ('resource', models.CharField(max_length=100, verbose_name='需求来源')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '排查',
                'verbose_name_plural': 'HW排查数据表',
                'ordering': ('-serial_number',),
            },
        ),
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(verbose_name='IP地址')),
                ('location', models.CharField(max_length=250, verbose_name='位置')),
                ('belong', models.CharField(max_length=250, verbose_name='归属')),
                ('note', models.CharField(max_length=250, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'IP白名单',
                'verbose_name_plural': 'IP白名单',
                'ordering': ('ip',),
            },
        ),
    ]
