# Generated by Django 2.1.7 on 2019-06-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(verbose_name='IP地址')),
                ('location', models.CharField(max_length=250, verbose_name='位置')),
                ('belong', models.CharField(max_length=250, verbose_name='归属')),
                ('type', models.CharField(max_length=10, verbose_name='黑白名单')),
                ('note', models.CharField(max_length=250, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'IP名单',
                'verbose_name_plural': 'IP名单',
                'ordering': ('ip',),
            },
        ),
        migrations.DeleteModel(
            name='BlackList',
        ),
        migrations.DeleteModel(
            name='WhiteList',
        ),
        migrations.AlterModelOptions(
            name='fengdu',
            options={'ordering': ('-serial_number', 'income_time'), 'verbose_name': 'HW封堵', 'verbose_name_plural': 'HW封堵数据表'},
        ),
    ]
